---
title: ""
format: docx
editor: visual
---

## Βιογραφικό Καθηγητή Αργύρη Στριγγάρη, MD, PhD, FRCPsych

**Καθηγητής Ψυχιατρικής Παιδιών και Εφήβων, Α´Ψυχιατρική Κλινική, Αιγινήτειο Νοσοκομείο, ΕΚΠΑ**

**Professor of Child & Adolescent Psychiatry, University College London**

[a.stringaris\@ucl.ac.uk](mailto:a.stringaris@ucl.ac.uk){.email}, [astringaris\@med.uoa.gr](mailto:astringaris@med.uoa.gr){.email}\
1-19 Torrington Pl, London WC1E 7HB, United Kingdom\
my UCL [website](https://www.ucl.ac.uk/psychiatry/professor-argyris-stringaris)\
AIM lab's [website](https://brainlog.blog/) and [github](https://github.com/transatlantic-comppsych)\
AIM clinic's [website](https://www.ucl.ac.uk/university-clinic/about-university-clinic/clinical-services/anxiety-self-image-and-mood-aim-clinic)

5η Ιουνίου 2024

Είμαι κλινικός ιατρός και νευροεπιστήμονας και από τον Ιανουάριο του 2022 κατέχω την Έδρα της Παιδοψυχιατρικής και Εφηβικής Ψυχιατρικής στο UCL και είμαι Καθηγητής Ψυχιατρικης Παιδιών και Εφήβων στο ΕΚΠΑ. Είμαι επίσης Αντυπρύτανης στο UCL για την Ψυχική Υγεία και Ευημερία. Μέχρι το 2022 ήμουν Senior Investigator και Επικεφαλής του Τμήματος Κλινικής και Υπολογιστικής Ψυχιατρικής στο NIMH/NIH στις ΗΠΑ και πριν από αυτό Αναπληρωτής Καθηγητής και Υπότροφος του Wellcome Trust στο Ινστιτούτο Ψυχιατρικής, Ψυχολογίας και Νευροεπιστημών, King's College London. Εκπαιδεύτηκα στην Παιδοψυχιατρική και Εφηβική Ψυχιατρική στο Νοσοκομείο Maudsley.
  Έχω δύο κύριους ερευνητικούς στόχους που επιδιώκω χρησιμοποιώντας πρακτικές ανοιχτής επιστήμης, συμπεριλαμβανομένης της κοινοποίησης δεδομένων και κώδικα.
  Όσον αφορά τη βασική έρευνα, στόχος μου είναι να κατανοήσω πώς γεννώνται και συντηρούνται τα συναισθηματικά φαινόμενα (που ονομάζονται μεταβλητά διαθέσεις, συναισθήματα, αισθήσεις ή συγκινήσεις). Αυτή τη στιγμή χρηματοδοτούμαστε από το Wellcome Trust για να μελετήσουμε τις εκπλήξεις (σφάλματα πρόβλεψης) ως μηχανισμό βελτίωσης στην κοινωνική αγχώδη διαταραχή.
  Όσον αφορά την κλινική έρευνα, μελετώ παρεμβάσεις που μειώνουν τον αρνητικό αντίκτυπο που έχουν τα συναισθηματικά φαινόμενα στους νέους και τις οικογένειες και τις πιθανές παρεμβάσεις. Προσπαθώ επίσης να αυξήσω την ευαισθητοποίηση σχετικά με τις στατιστικές και τις ερμηνείες για τη δημόσια υγεία μέσω της δουλειάς μου.


Το h-index μου είναι 63  και εδώ οι [δημοσιεύσεις μου στο PubMed](https://pubmed.ncbi.nlm.nih.gov/?term=stringaris+a&sort=date) και η σελιδα μου  στο [Google Scholar](https://scholar.google.com/citations?user=9B82424AAAAJ&hl=en&oi=ao).

### Θέσεις που Κατέχω

**Professor of Child and Adolescent Psychiatry**\
University of Athens, Greece\

**Professor of Child and Adolescent Psychiatry**\
Division of Psychiatry and Department of Clinical, Educational & Health
Psychology University College London\
Co-Director (with Dr Georgina Krebs) of Anxiety self-Image and Mood
(AIM)
[Lab](https://www.ucl.ac.uk/pals/research/clinical-educational-and-health-psychology/research-groups/aim-lab)
and
[Clinic](https://www.ucl.ac.uk/university-clinic/about-university-clinic/clinical-services/anxiety-self-image-and-mood-aim-clinic)
at UCL.

**Pro-Vice-Provost UCL Grand Challenges in Mental Health and
Wellbeing**\

### Άλλες θέσεις που κατέχω
**Visiting Scientist and Head of the Clinical Neuroscience of Mood
Disorders in Children and Adolescents**\
Central Institute of Mental Health (Zentralinstitut für Seelische
Gesundheit), Mannheim, Germany\
**Honorary Consultant Child & Adolescent Psychiatrist**\
Camden & Islington NHS Foundation Trust\
**Senior Clinical Advisor** Anna Freud Centre

### Εκπαίδευση και Πτυχία

**Ιατρική Εκπαίδευση και Πτυχία/Άδειες Ασκήσεως Επαγγέλαμτος**

-   May 2000 Πτυχίο Ιατρικής University of Göttingen, Germany. Top 3% όλων των φοιτητών της χώρας στις τελικές  Παγγερμανικές γραπτές και προφορικες εξετάσεις στο 5ο έτος.
 (II Staatsexamen) και στο 20% όλων των φοιτητών της χώρας στις προφορικές του 6ου έτους. 
-   Registration with the UK General Medical Council: 6043066
-   Registration with the Maryland Board of Physicians by "Conceded
    Eminence": D48427
-   Entry into the UK Specialist Register for Child and Adolescent
    Psychiatry (CCT): 2011
-   Royal College of Psychiatrists Membership: 813569, Από το 2018 Εταίρος του Κολλεγίου.
-   Hellenic Medical Council: Certified Specialist in Child and
    Adolescent Psychiatry

**Εκπαίδευση στην Έρευνα**

-   Διδακτορική Διατριβή στις Αναπτυξιακές Νευροεπσιτήμες, PhD: King’s College London, University of London, UK, May 2011
    (Επόπτες: Prof Eric Taylor/Prof Robert Goodman)
-   Ερευνητικός Εταίρος, NIMH, USA, Jul 2008 –
    Jul 2009 (Επόπτης: Dr Ellen Leibenluft)
-   Διδακτορική Διατριβή στην Νευρολογία, Dr med (MD Research), Department of Neurology, University of
    Göttingen, Germany, May 2000 (Επόπτης: Prof Roland Nau)

**Εκπαίδευση στην Νευρολογία και Ψυχιατρική**

-   Aug 2006 – Apr 2011: Higher Specialist Training in Child and
    Adolescent Psychiatry, Maudsley Hospital and Great Ormond Street and
    Royal London Rotation
-   Jul 2006: Membership, Royal College of Psychiatrists (MRCPsych,
    London, UK)
-   Oct 2003 - Aug 2006: Senior House Officer, Maudsley Hospital,
    London, UK
-   Oct 2002 - Oct 2003: Senior House Officer, Maudsley Hospital,
    London, UK and Institute of Psychiatry, London, UK
-   Jun 2000 - Oct 2002: Neurology and Medicine, University of
    Göttingen, Germany

------------------------------------------------------------------------

### Προηγούμενη Εργασία

-   August 2016 to 2021: Επικεφαλής (Chief) Section of Clinical & Computational
    Psychiatry, NIMH, NIH
-   Jan 2012 - August 2016 Αναπληρωτής Καθηγητής (Senior Lecturer),Department of Child & Adolescent Psychiatry, Institute
    of Psychiatry, Psychology & Neuroscience, King’s College London &
    Maudsley Hospital London
-   Apr 2011 – August 2016: Διευθυντής (Consultant) Ψυχίατρος Maudsley Hospital
-   Jan 2007 - Jan 2012: Lecturer in Child and Adolescent Psychiatry at
    Institute of Psychiatry, King’s College London, London, UK με περίοδο ενός έτους ως εταίρος στο National Institute of Mental Health,
    Bethesda, USA μεταξύ Ιουλίου 2008 και Ιουλίου 2009.
-   Jan 2007 - Apr 2011: Ειδικευόμενος (Specialist Registrar), Maudsley Hospital,
    London, UK
-   Aug 2006 - Dec 2006: Ειδικευόμενος (Specialist Registrar) in Child and
    Adolescent Psychiatry, Great Ormond Street and Royal London
    Rotation, London, UK
-   Apr 2006 – Aug 2006: Ειδικευόμενος (Senior House Officer) Maudsley and King’s College Hospitals, General
    Liaison and Perinatal Psychiatry, London, UK
-   Oct 2002 - Aug 2006: Ειδικευόμενος (Senior House Officer), South London and Maudsley
    NHS General Psychiatry Training Rotation, London, UK
-   Jun 2000 - Oct 2002: Ειδικευόμενος (Assistenzarzt),
    Department of Neurology, University of Göttingen, Germany

## Ηγετικές Θέσεις (ενδεικτικά) 

**Αντιπρύτανης **

-   UCL's Grand Challenges in Mental Health and Wellbeing μαζί με την
    Prof. Essi Viding

**Πρόεδρος Διεθνούς Οργανισμού**

-   Past President of the [International Society for Research in Child
    and Adolescent Psychopathology
    (ISRCAP)](https://isrcap.org/executive-committee.html)

**Πρόεδρος Κυβερνητικών Επιτροπών**

-   Πρόεδρος Επιτροπής Ψυχικής Υγείας Κεντρικού Συμβουλίου Υγείας (ΚΕΣΥ) Ελλάαδος.

### Βραβεύσεις (ενδεικτικά)

-   2024 Editor's Choice Prize for our paper with Dr Foulkes "Do No
    Harm: Can School Mental Health Interventions Cause Iatrogenic Harm."
    BJPsych Bulletin.
-   2022 Highly Cited Researcher Clarivate Analytics
-   2021 Open Neuro Hall of Fame, tied 2nd Place for contributing
    datasets
-   2021 Kramer Pollnow Prize Award for scientific excellence in
    clinical research in child,adolescent and adult psychiatry by the
    European Network of Hyperactivity Disorders (EUNETHYDIS)
-   2020 Elaine Schlosser Lewis Award as the best research paper in ADHD
-   2019 NIH Director’s Award “for exemplary performance while
    demonstrating significant leadership, skill and ability in serving
    as a mentor.”
-   2019 Gerald L Klerman Young Investigator (under 45 years) Prize
-   2019 Prize for Distinguished Editorial Contributions, Academy of
    Child and Adolescent Mental Health, J Child Psychol and Psychiatry
-   2018 Εκλογή ως Εταίρου του Royal College of Psychiatrists UK for
    Distinct and Significant Contributions to psychiatry.
    
### Χρηματοδοτήσεις (ενδεικτικά)

-   Title: Surprises as a Mechanism of Improvement in the Psychological
    Therapy of Anxiety and Depression in Young People\
    Position: PI\
    Funding Body: Wellcome Trust\
    Amount:£3,015,694.19\
    Outcome: awarded December 2022

-   Title: How does the SSRI fluoxetine work in adolescent depression?\
    Position: Co-I and site PI (overall PI Prof Harmer, Oxford)\
    Funding Body: Wellcome Trust\
    Amount:£2,570,720.00\
    Outcome: awarded December 2022
-   Title: 4M: Microbes, Milk, Mental Health and Me; how do early life
    gut microbiota and feeding shape long- term mental health in the
    C-GULL Cohort?\
    Position: Co-Investigator (5% of my time)\
    Funding Body: Wellcome Trust\
    Amount: £6,923,603.00\
    Dates: awarded FY23 to FY 28
    
### Εκπαιδευτικό Έργο (συνοπτικά)
Εποπτέυω ή έχω εποπτεύσει άνω των 10 διδακτορικών φοιτητών, άνω των 20 μεταπτυχιακών (MSc) καθώς και μεγάλο αριθμό φοιτητών ιατρικής. Ήμουν ο Υπεύθυνος για την Ακαδημαϊκή Εκπαίδευση των Ειδικευομένων Παιδοψυχιατρικής στο Νοσοκομείο Maudsley. Έχω βραβευθεί για το Εκπαιδευτικό μου έργο με τα 2019
NIH Director’s Award “for exemplary performance and significant
leadership, skill and ability in serving as a mentor.” - 2018
Outstanding Mentor Award by the National Institutes of Mental Health


### Δημοσιεύσεις (Ενδεικτικά)

**Βιβλία (ενδεικτικά)**
**Stringaris** A & Taylor E (2015). Disruptive Mood: Irritability in
Children and Adolescents. New York: Oxford University Press.


Thapar A, Pine D, **Stringaris** A, Ford T, Cresswell C, Cortese S,
Leckman J (in preparation) Rutter’s Textbook of Child Psychiatry and
Psychology, Oxford, UK: Wiley Blackwell

Broome MR, Harland R, Owen GS, **Stringaris** A (2012). The Maudsley
Reader in Phenomenological Psychiatry. Cambridge, UK: Cambridge
University Press

**Stringaris A** (2024) Use of Structured Interviews, Rating Scales and
Observational Methods in Clinical Settings. In Thapar A, Pine D,
**Stringaris** A, Ford T, Cresswell C, Cortese S, Leckman J (in
preparation) Rutter’s Textbook of Child Psychiatry and Psychology,
Oxford, UK: Wiley Blackwell

**Δημοσιεύσεις σε διεθνή περιοδικά με κρίση (ενδεικτικά)**
Krebs G, Clark BR, Ford TJ,StringarisA. (2024) Epidemiology of Body Dysmorphic Disorder andAppearance Preoccupation in Youth: Prevalence, Comorbidity and Psychosocial ImpairmentJ Am AcadChild Adolesc PsychiatryPMID:38508411

Leibenluft E, ... Vidal-Ribas P, Wakschlag LS,Stringaris A. (2024) Irritability in Youths: A Critical Integrative Review Am J Psychiatry PMID:38419494

Mantas V, Kotoula V, Zheng C, Nielson DM,Stringaris A. (2023) An experimental approach totraining mood for resilience PLoS One PMID:37676862

Carey EG, Ridler I, Ford TJ,Stringaris A. (2023) Editorial Perspective: When is a ‘small effect’actually large and impactful? J Child Psychol Psychiatry PMID:37226639

Jangraw DC, Keren H, Sun H, Bedder RL, Rutledge RB, Pereira F, Thomas AG, Pine DS, Zheng C,Nielson DM,Stringaris A. (2023) A highly replicable decline in mood during rest and simple tasks NatHum Behav PMID:36849591

Foulkes L,Stringaris A. (2023) Do no harm: can school mental health interventions cause iatrogenicharm? BJPsych Bull PMID:3684344425. 

Keren H, Zheng C, Jangraw DC, Chang K, Vitale A, Rutledge RB, Pereira F, Nielson DM,Stringaris A. (2021) The temporal representation of experience in subjective mood Elife PMID:34128464
 
Vidal-Ribas P, Janiri D, Doucet GE, Pornpattananangkul N, Nielson DM, Frangou S,Stringaris A.(2021) Multimodal Neuroimaging of Suicidal Thoughts and Behaviors in a U.S. Population-Based Sample of School-Age Children Am J Psychiatry PMID:33472387
 
Nielson DM, Keren H, O’Callaghan G, Jackson SM, Douka I, Vidal-Ribas P, Pornpattananangkul N,Camp CC, Gorham LS, Wei C, Kirwan S, Zheng CY,Stringaris A. (2021) Great Expectations: A CriticalReview of and Suggestions for the Study of Reward Processing as a Cause and Predictor of Depression BiolPsychiatry PMID:32797941
  
Pornpattananangkul N, Leibenluft E, Pine DS,Stringaris A. (2020) Association between childhood anhedonia and alterations inlarge-scale resting-state networks and task-evoked activation. JAMA Psychiatry. 2019;76(6):624-633 JAMA Psychiatry PMID:32629467
