---
title: "Professor Argyris Stringaris Select Publications"
date: "19/01/2023"
output:
  word_document: default
  html_document: default
  pdf_document: default
---
- Jangraw DC, Keren H, Bedder RL, Rutledge RB, Perreira F, Thomas AG,Pine DS, Zheng C, Nielson, DM , Stringaris A (2022) A Highly Replicable Decline in Mood During Rest and Simple Tasks, **Nature Human Behaviour** (in press)
- Tang A, Harrewijn A, Benson B, Haller SP, Guyer AE, Perez-Edgar KE, Stringaris A, Ernst M, Brotman MA, Pine DS, Fox NA. (2022) Striatal Activity to Reward Anticipation as a Moderator of the Association Between Early Behavioral Inhibition and Changes in Anxiety and Depressive Symptoms From Adolescence to Adulthood **JAMA Psychiatry** PMID:36287532
- Tetereva A, Li J, Deng JD, Stringaris A, Pat N. (2022) Capturing brain-cognition relationship: Integrating task-based fMRI across tasks markedly boosts prediction and test-retest reliability **Neuroimage** PMID:36057404
- Pat N, Wang Y, Anney R, Riglin L, Thapar A, Stringaris A. (2022) Longitudinally stable, brain-based predictive models mediate the relationships between childhood cognition and socio-demographic, psychological and genetic factors **Hum Brain Mapp** PMID:35903877
- Pat N, Wang Y, Bartonicek A, Candia J, Stringaris A. (2022) Explainable machine learning approach to predict and explain the relationship between task-based fMRI and individual differences in cognition **Cereb Cortex** PMID:35697648
- Pan PM, Sato JR, Paillère Martinot ML, Martinot JL, Artiges E, Penttilä J, Grimmer Y, van Noort BM, Becker A, Banaschewski T, Bokde ALW, Desrivières S, Flor H, Garavan H, Ittermann B, Nees F, Papadopoulos Orfanos D, Poustka L, Fröhner JH, Whelan R, Schumann G, Westwater ML, Grillon C, Cogo-Moreira H, Stringaris A, Ernst M; IMAGEN Consortium. (2022) Longitudinal Trajectory of the Link Between Ventral Striatum and Depression in Adolescence **Am J Psychiatry** PMID:35582783
- Sadeghi N, Fors PQ, Eisner L, Taigman J, Qi K, Gorham LS, Camp CC, O’Callaghan G, Rodriguez D, McGuire J, Garth EM, Engel C, Davis M, Towbin KE, Stringaris A, Nielson DM. (2022) Mood and Behaviors of Adolescents With Depression in a Longitudinal Study Before and During the COVID-19 Pandemic **J Am Acad Child Adolesc Psychiatry** PMID:35452785
- Liuzzi L, Chang KK, Zheng C, Keren H, Saha D, Nielson DM, Stringaris A. (2022) Magnetoencephalographic correlates of mood and reward dynamics in human adolescents **Cereb Cortex** PMID:34921602
- Pat N, Riglin L, Anney R, Wang Y, Barch DM, Thapar A, Stringaris A. (2022) Motivation and Cognitive Abilities as Mediators Between Polygenic Scores and Psychopathology in Children **J Am Acad Child Adolesc Psychiatry** PMID:34506929
- Keren H, Zheng C, Jangraw DC, Chang K, Vitale A, Rutledge RB, Pereira F, Nielson DM, Stringaris A. (2021) The temporal representation of experience in subjective mood **Elife** PMID:34128464
- Kotoula V, Stringaris A, Mackes N, Mazibuko N, Hawkins PCT, Furey M, Curran HV, Mehta MA. (2022) Ketamine Modulates the Neural Correlates of Reward Processing in Unmedicated Patients in Remission From Depression Biol Psychiatry Cogn Neurosci **Neuroimaging** PMID:34126264
- Vidal-Ribas P, Janiri D, Doucet GE, Pornpattananangkul N, Nielson DM, Frangou S, Stringaris A. (2021) Multimodal Neuroimaging of Suicidal Thoughts and Behaviors in a U.S. Population-Based Sample of School-Age Children **Am J Psychiatry** PMID:33472387
- Nielson DM, Keren H, O’Callaghan G, Jackson SM, Douka I, Vidal-Ribas P, Pornpattananangkul N, Camp CC, Gorham LS, Wei C, Kirwan S, Zheng CY, Stringaris A. (2021) Great Expectations: A Critical Review of and Suggestions for the Study of Reward Processing as a Cause and Predictor of Depression **Biol Psychiatry** PMID:32797941
- Monzani B, Vidal-Ribas P, Turner C, Krebs G, Stokes C, Heyman I, Mataix-Cols D, Stringaris A. (2020) The Role of Paternal Accommodation of Paediatric OCD Symptoms: Patterns and Implications for Treatment Outcomes **J Abnorm Child Psychol** PMID:32683586
- Cuijpers P, Stringaris A, Wolpert M. (2020) Treatment outcomes for depression: challenges and opportunities **Lancet Psychiatry** PMID:32078823
- Dwyer JB, Stringaris A, Brent DA, Bloch MH. (2020) Annual Research Review: Defining and treating pediatric treatment-resistant depression **J Child Psychol Psychiatry** PMID:32020643
- Vidal-Ribas P, Benson B, Vitale AD, Keren H, Harrewijn A, Fox NA, Pine DS, Stringaris A. (2019) Bidirectional Associations Between Stress and Reward Processing in Children and Adolescents: A Longitudinal Neuroimaging Study **Biol Psychiatry Cogn Neurosci Neuroimaging** PMID:31324591
- Riglin L, Eyre O, Thapar AK, Stringaris A, Leibenluft E, Pine DS, Tilling K, Davey Smith G, O’Donovan MC, Thapar A. (2019) Identifying Novel Types of Irritability Using a Developmental Genetic Approach **Am J Psychiatry** PMID:31256611
- Towbin K, Vidal-Ribas P, Brotman MA, Pickles A, Miller KV, Kaiser A, Vitale AD, Engel C, Overman GP, Davis M, Lee B, McNeil C, Wheeler W, Yokum CH, Haring CT, Roule A, Wambach CG, Sharif-Askary B, Pine DS, Leibenluft E, Stringaris A. (2020) A Double-Blind Randomized Placebo-Controlled Trial of Citalopram Adjunctive to Stimulant Medication in Youth With Chronic Severe Irritability **J Am Acad Child Adolesc Psychiatry** PMID:31128268
- Pornpattananangkul N, Leibenluft E, Pine DS, Stringaris A. (2019) Association Between Childhood Anhedonia and Alterations in Large-scale Resting-State Networks and Task-Evoked Activation **JAMA Psychiatry** PMID:30865236
- Wolke SA, Mehta MA, O’Daly O, Zelaya F, Zahreddine N, Keren H, O’Callaghan G, Young AH, Leibenluft E, Pine DS, Stringaris A. (2019) Modulation of anterior cingulate cortex reward and penalty signalling in medication-naive young-adult subjects with depressive symptoms following acute dose lurasidone **Psychol Med** PMID:30606271
- Vidal-Ribas P, Brotman MA, Salum GA, Kaiser A, Meffert L, Pine DS, Leibenluft E, Stringaris A. (2018) Deficits in emotion recognition are associated with depressive symptoms in youth with disruptive mood dysregulation disorder **Depress Anxiety** PMID:30004611
- Keren H, O’Callaghan G, Vidal-Ribas P, Buzzell GA, Brotman MA, Leibenluft E, Pan PM, Meffert L, Kaiser A, Wolke S, Pine DS, Stringaris A. (2018) Reward Processing in Depression: A Conceptual and Meta-Analytic Review Across fMRI and EEG Studies **Am J Psychiatry** PMID:29921146
- Villalta L, Smith P, Hickin N, Stringaris A. (2018) Emotion regulation difficulties in traumatized youth: a meta-analysis and conceptual review **Eur Child Adolesc Psychiatry** PMID:29380069
- Fernández de la Cruz L, Vidal-Ribas P, Zahreddine N, Mathiassen B, Brøndbo PH, Simonoff E, Goodman R, Stringaris A. (2018) Should Clinicians Split or Lump Psychiatric Symptoms? The Structure of Psychopathology in Two Large Pediatric Clinical Samples from England and Norway **Child Psychiatry Hum Dev** PMID:29243079
- Pan PM, Sato JR, Salum GA, Rohde LA, Gadelha A, Zugman A, Mari J, Jackowski A, Picon F, Miguel EC, Pine DS, Leibenluft E, Bressan RA, Stringaris A. (2017) Ventral Striatum Functional Connectivity as a Predictor of Adolescent Depressive Disorder in a Longitudinal Community-Based Sample **Am J Psychiatry** PMID:28946760
- Mikita N, Simonoff E, Pine DS, Goodman R, Artiges E, Banaschewski T, Bokde AL, Bromberg U, Büchel C, Cattrell A, Conrod PJ, Desrivières S, Flor H, Frouin V, Gallinat J, Garavan H, Heinz A, Ittermann B, Jurk S, Martinot JL, Paillère Martinot ML, Nees F, Papadopoulos Orfanos D, Paus T, Poustka L, Smolka MN, Walter H, Whelan R, Schumann G, Stringaris A. (2016) Disentangling the autism-anxiety overlap: fMRI of reward processing in a community-based longitudinal study **Transl Psychiatry** PMID:27351599
- Vidal-Ribas P, Brotman MA, Valdivieso I, Leibenluft E, Stringaris A. (2016) The Status of Irritability in Psychiatry: A Conceptual and Quantitative Review **J Am Acad Child Adolesc Psychiatry** PMID:27343883
